services:
  backend:
    build: ./backend
    container_name: backend
    #network_mode: host
    ports:
      - "5000:5000"
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    command: ["node", "index.js"]
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    environment:
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
    depends_on:
      - backend
    restart: always