[phases]
setup = [
    "cd backend && pip install -r requirements.txt",
    "npm install --prefix backend",
    "npm install --prefix frontend"
]

[build]
build = "npm run build --prefix frontend"

[start]
start = "cd backend && npm start"
