# nixpacks.toml (Version Définitive)

[phases.setup]
# Installe Node.js ET Python/pip. C'est la première chose qui se passe.
nixPkgs = ["nodejs-20", "python311", "python311Packages.pip"]

[phases.build]
# DÉFINIT toutes les étapes de build dans le BON ORDRE
cmds = [
    "pip install -r backend/requirements.txt",
    "npm install --prefix backend",
    "npm install --prefix frontend",
    "npm run build --prefix frontend"
]

[start]
# La commande pour démarrer le serveur une fois le build terminé
cmd = "npm start --prefix backend"
