# nixpacks.toml (Version finale pour Railway)

[phases.setup]
# Dit à Nixpacks d'inclure les paquets par défaut (Node.js)
# ET d'y AJOUTER Python et pip. C'est l'étape cruciale.
nixPkgs = ["...", "python311", "python311Packages.pip"]

# On ne définit PAS les autres phases (install, build, start).
# Cela force Railway à utiliser les scripts de votre package.json,
# ce qu'il fait déjà, mais cette fois dans le bon environnement.
