# nixpacks.toml (Version Corrigée pour Railway)

[phases.setup]
# Installe Node.js (via le provider standard) et Python
# C'est l'étape la plus importante pour corriger "pip: not found"
nixPkgs = ["nodejs-20", "python311", "python311Packages.pip"]

[start]
# Commande pour démarrer le serveur une fois le build terminé
cmd = "npm start --prefix backend"
